## Basic Configuration

baseurl = "http://www.remkoduursma.com"
builddrafts = false
canonifyurls = false
languageCode = "en-US"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"

author = "Remko Duursma"
title = "Remko Duursma"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "UA-10108116-1"
enableRobotsTXT = true

## Site Settings
[params]
author = "Remko Duursma"
intro = "Data Scientist, searching..."
description = "Looking for a new challenge."
authorimage = "remko.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Remko Duursma's Homepage"
keywords = "data science, R, programming, data analysis, blog"

## Social Accounts
[params.social]
github = "RemkoDuursma"
linkedin = "remkoduursma"
stackoverflow = "1758082"
email = "remkoduursma@gmail.com"
gscholar = "qGSIWxcAAAAJ"
bitbucket = "remkoduursma"

## Extras
[params.extra]
copyright = "© 2017-2018. Remko Duursma." 
poweredby = true
highlightjs = true

## Main Menu

#[[menu.main]]
#    name = "about"
#    identifier = "about"
#    weight = 200
#    url = "/about/"

[[menu.main]]
    name = "Publications"
    identifier = "publications"
    weight = 200
    url = "/pages/publications_full/"
[[menu.main]]
    name = "R Blog"
    weight = 100
    identifier = "blog"
    url = "/post/"
[[menu.main]]
    name = "R Course"
    identifier = "rcourse"
    weight = 200
    url = "http://www.hiercourse.com"
[[menu.main]]
    name = "R Packages"
    identifier = "rpackages"
    weight = 200
    url = "/post/2017-11-10-rpackages/index.html"



