## Basic Configuration

baseurl = "http://www.remkoduursma.com"
builddrafts = false
canonifyurls = false
languageCode = "en-US"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

contentdir = "content"
layoutdir = "layouts"
publishdir = "docs"

author = "Remko Duursma"
title = "Remko Duursma"

theme = "hugo-goa"

## Hugo Built-in Features
#disqusShortname = "https-shenoybr-github-io-hugo-goa-demo" # Comment out to disable Disqus.
googleAnalytics = "UA-10108116-1"
enableRobotsTXT = true

## Site Settings
[params]
author = "Remko Duursma"
intro = "Data Scientist, R Programmer, R Trainer, Scientist."
description = ""
authorimage = "remko.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Remko Duursma's Homepage"
keywords = "data science, R, programming, training, data analysis, blog"

## Social Accounts
[params.social]
github = "RemkoDuursma"
linkedin = "remkoduursma"
stackoverflow = "1758082"
email = "remkoduursma@gmail.com"
##gscholar = "qGSIWxcAAAAJ"
bitbucket = "remkoduursma"

## Extras
[params.extra]
copyright = "© 2017-2018. Remko Duursma." 
poweredby = true
highlightjs = true

[markup.goldmark.renderer]
unsafe= true

## Main Menu

#[[menu.main]]
#    name = "about"
#    identifier = "about"
#    weight = 200
#    url = "/about/"

#[[menu.main]]
#    name = "Available Training and Services"
#    identifier = "training"
#	weight = 1
#	url ="/training/index.html"

[[menu.main]]
    name = "Bio"
    identifier = "bio"
    weight = 1
    url = "/pages/bio/"
[[menu.main]]
    name = "R Packages, R code, and R Blog"
    weight = 2
    identifier = "rcode"
    url = "/pages/rcode/"


